=== hrguarinv/mct-1.7.3/ImportExportProvider/src/main/resources/importExportSchema/importExport.xsd
<?xml version="1.0" encoding="ISO-8859-5" ?>
<xsd:schema xmlns="http://gov.nasa.arc.mct" targetNamespace="http://gov.nasa.arc.mct"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  attributeFormDefault="unqualified">
  <xsd:annotation>
    <xsd:appinfo>Interface for importing and exporting MCT components.</xsd:appinfo>
  </xsd:annotation>

  <!-- component within components must be unique-->
  <xsd:element name="components" type="ComponentListType">
    <xsd:key name="componentsKey">
      <xsd:selector xpath="./component"/>
      <xsd:field xpath="@componentId"/>
    </xsd:key>
  </xsd:element>

  <xsd:complexType name="ComponentListType">
    <xsd:sequence>
      <xsd:element name="component" type="ComponentType" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="schemaVersion" type="xsd:decimal" use="required" fixed="1.0"/>
    <xsd:attribute name="origin" type="xsd:string" use="optional"/>
  </xsd:complexType>

  <xsd:complexType name="ComponentType">
    <xsd:sequence>
      <xsd:element name="associatedComponents" type="AssociatedComponentType" nillable="true"
        minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="componentRefs" type="ComponentRefType"  minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="modelState" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="tags" type="NameValueType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="viewStates" type="NameValueType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="componentId" type="xsd:string" use="required"/>
    <xsd:attribute name="componentType" type="xsd:string" use="required"/>
    <xsd:attribute name="creationDate" type="xsd:dateTime" use="required"/>
    <xsd:attribute name="creator" type="xsd:string" use="required"/>
    <xsd:attribute name="externalKey" type="xsd:string"/>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
    <xsd:attribute name="owner" type="xsd:string" use="required"/>
    <xsd:attribute name="toplevel" type="xsd:boolean" use="required"/>
  </xsd:complexType>
  
   <xsd:complexType name="NameValueType">
    <xsd:sequence>
      <xsd:element name="key" minOccurs="0" type="xsd:string"/>
      <xsd:element name="value" minOccurs="0" type="xsd:string"/>
    </xsd:sequence>
   </xsd:complexType>
  
  <xsd:complexType name="AssociatedComponentType">
    <xsd:attribute name="id" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="ComponentRefType">
    <xsd:attribute name="componentId" type="xsd:string" use="required"/>
    <xsd:attribute name="externalKey" type="xsd:string" use="required"/>
    <xsd:attribute name="classType"   type="xsd:string" use="required"/>
  </xsd:complexType>

</xsd:schema>

=== hrguarinv/mct-1.7.3/ImportExportProvider/src/test/resources/testData/testBadClassType.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<components xmlns="http://gov.nasa.arc.mct" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" schemaVersion="1" xsi:schemaLocation="http://gov.nasa.arc.mct importExport.xsd">
    <component toplevel="true" owner="jimbooster" name="BadClassType" creator="jimbooster" creationDate="2012-06-05T14:11:49.000-05:00" componentType="gov.nasa.arc.mct.components.collection.CollectionComponent" componentId="e0bc743521aa46de95b8d533905577a0">
        <associatedComponents id="e88f846930b3464ba65e03db70acc0ac"/>
    </component>
    <component toplevel="false" owner="jimbooster" name="Col A" creator="jimbooster" creationDate="2012-06-05T14:12:29.000-05:00" componentType="gov.nasa.arc.mct.components.collection.WeirdComponent" componentId="e88f846930b3464ba65e03db70acc0ac">
        <associatedComponents id="f5c351b5b7a14e0b9006774fdaa30274"/>
        <associatedComponents id="f33fd27b111345e8a75f4c7c69afc268"/>
    </component>
    <component toplevel="false" owner="jimbooster" name="telemetry obj" creator="jimbooster" creationDate="2012-06-05T14:12:45.000-05:00" componentType="org.acme.example.telemetry.TelemetryComponent" componentId="f5c351b5b7a14e0b9006774fdaa30274">
    </component>
    <component toplevel="false" owner="jimbooster" name="Col B" creator="jimbooster" creationDate="2012-06-05T14:13:03.000-05:00" componentType="gov.nasa.arc.mct.components.collection.CollectionComponent" componentId="f33fd27b111345e8a75f4c7c69afc268">
        <associatedComponents id="e88f846930b3464ba65e03db70acc0ac"/>
        <associatedComponents id="f40002fdb04749129700dbd5618b8860"/>
    </component>
    <component toplevel="false" owner="jimbooster" name="telemetry obj 2" creator="jimbooster" creationDate="2012-06-05T14:13:27.000-05:00" componentType="org.acme.example.telemetry.TelemetryComponent" componentId="f40002fdb04749129700dbd5618b8860">
    </component>
</components>

=== hrguarinv/mct-1.7.3/ImportExportProvider/src/test/resources/testOutput/multComp.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<components xmlns="http://gov.nasa.arc.mct" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" schemaVersion="1" xsi:schemaLocation="http://gov.nasa.arc.mct importExport.xsd">
    <component toplevel="true" owner="Fred" name="Test Name" creator="Ginger" creationDate="2012-07-31T14:05:46.137-07:00" componentType="gov.nasa.arc.mct.importExport.provider.ExporterTest$TestAbstractComponent" componentId="PARENT">
        <associatedComponents id="CHILD"/>
        <modelState>&lt;testModel/&gt;</modelState>
        <viewStates>
            <key>test1</key>
            <value>&lt;extendedInfo&gt;&lt;viewRoleProperties&gt;&lt;entries key=&quot;viewType1&quot;&gt;&lt;value&gt;properties1&lt;/value&gt;&lt;/entries&gt;&lt;entries key=&quot;viewType2&quot;&gt;&lt;value&gt;properties2&lt;/value&gt;&lt;/entries&gt;&lt;/viewRoleProperties&gt;&lt;/extendedInfo&gt;</value>
        </viewStates>
        <viewStates>
            <key>test2</key>
            <value>&lt;extendedInfo&gt;&lt;viewRoleProperties&gt;&lt;entries key=&quot;viewType1&quot;&gt;&lt;value&gt;properties1&lt;/value&gt;&lt;/entries&gt;&lt;entries key=&quot;viewType2&quot;&gt;&lt;value&gt;properties2&lt;/value&gt;&lt;/entries&gt;&lt;/viewRoleProperties&gt;&lt;/extendedInfo&gt;</value>
        </viewStates>
    </component>
    <component toplevel="false" owner="Fred" name="Test Name" creator="Ginger" creationDate="2012-07-31T14:05:46.137-07:00" componentType="gov.nasa.arc.mct.importExport.provider.ExporterTest$TestAbstractComponent" componentId="CHILD">
        <associatedComponents id="PARENT"/>
        <modelState>&lt;testModel/&gt;</modelState>
        <viewStates>
            <key>test1</key>
            <value>&lt;extendedInfo&gt;&lt;viewRoleProperties&gt;&lt;entries key=&quot;viewType1&quot;&gt;&lt;value&gt;properties1&lt;/value&gt;&lt;/entries&gt;&lt;entries key=&quot;viewType2&quot;&gt;&lt;value&gt;properties2&lt;/value&gt;&lt;/entries&gt;&lt;/viewRoleProperties&gt;&lt;/extendedInfo&gt;</value>
        </viewStates>
        <viewStates>
            <key>test2</key>
            <value>&lt;extendedInfo&gt;&lt;viewRoleProperties&gt;&lt;entries key=&quot;viewType1&quot;&gt;&lt;value&gt;properties1&lt;/value&gt;&lt;/entries&gt;&lt;entries key=&quot;viewType2&quot;&gt;&lt;value&gt;properties2&lt;/value&gt;&lt;/entries&gt;&lt;/viewRoleProperties&gt;&lt;/extendedInfo&gt;</value>
        </viewStates>
    </component>
    <component toplevel="true" owner="Fred" name="Test Name" creator="Ginger" creationDate="2012-07-31T14:05:46.140-07:00" componentType="gov.nasa.arc.mct.importExport.provider.ExporterTest$TestAbstractComponent" componentId="PARENT">
        <associatedComponents id="CHILD"/>
        <modelState>&lt;testModel/&gt;</modelState>
        <viewStates>
            <key>test1</key>
            <value>&lt;extendedInfo&gt;&lt;viewRoleProperties&gt;&lt;entries key=&quot;viewType1&quot;&gt;&lt;value&gt;properties1&lt;/value&gt;&lt;/entries&gt;&lt;entries key=&quot;viewType2&quot;&gt;&lt;value&gt;properties2&lt;/value&gt;&lt;/entries&gt;&lt;/viewRoleProperties&gt;&lt;/extendedInfo&gt;</value>
        </viewStates>
        <viewStates>
            <key>test2</key>
            <value>&lt;extendedInfo&gt;&lt;viewRoleProperties&gt;&lt;entries key=&quot;viewType1&quot;&gt;&lt;value&gt;properties1&lt;/value&gt;&lt;/entries&gt;&lt;entries key=&quot;viewType2&quot;&gt;&lt;value&gt;properties2&lt;/value&gt;&lt;/entries&gt;&lt;/viewRoleProperties&gt;&lt;/extendedInfo&gt;</value>
        </viewStates>
    </component>
</components>
